name: SignToSign
main: net.gamesketch.bukkit.signToSign.SignToSign
version: 0.0.1
website: http://www.gamesketch.net
author: The GameSketch Community
description: >
             Fine grained teleportation links between signs.
commands:
